### ISSUE TITLE
Error when installing client

### ISSUE THREAD

**Issue by eggbean** [leonwind/cli2cloud#11]
I thought I'd try this out, but I am getting this error, currently using Windows WSL:

```
$ go install github.com/leonwind/cli2cloud/cli/cli2cloud@latest
package github.com/leonwind/cli2cloud/cli/cli2cloud@latest: cannot use path@version syntax in GOPATH mode
```

What do I do here?

**Comment by leonwind** [comment]
I'm gonna close this for now.
If there is anything I can help you with, let me know :)
