### ISSUE TITLE
Piped content avalability

### ISSUE THREAD

**Issue by CompuRoot** [leonwind/cli2cloud#16]
How long piped content to `cli3cloud.com` would be stored ?
I can see it works in real time as well content still available even output is stopped.

**Comment by leonwind** [comment]
Hi, for now, while the traffic is still small, the content will not get deleted at all and I am certain it will stay this way until my Postgres database will come to a limit, which is very unlikely to be honest.
If the database comes to a limit, which we are still very very far away from, you can expect that the output will be stored for at least a month.
