### ISSUE TITLE
Idea: support for ANSI escape codes

### ISSUE THREAD

**Issue by pidue** [leonwind/cli2cloud#17]
Idea: support for basic [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code), in particular [3-bit and 4-bit](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit).

Example:

Command: 
`echo -e "\033[0;31mRED\033[0m" | cli2cloud` 

Actual: 
![Actual](https://user-images.githubusercontent.com/15063785/160874184-ddf886d5-8a74-4772-b5b1-90edf57416a0.png)

Expected: 
![Expected](https://user-images.githubusercontent.com/15063785/160874414-923c5550-91eb-4bd7-9427-57867b67833e.png)

[ansi-to-html](https://www.npmjs.com/package/ansi-to-html) might provide some hints on how to convert ANSI sequence to HTML colors

**Comment by leonwind** [comment]
Hi, this is a very good idea. Totally missed this.
I am currently taking some time off but I will take a look at this by next week :)

**Comment by leonwind** [comment]
Hi, I added ANSI support now and it seems to work :)
See here: https://cli2cloud.com/6PEQ8N displaying your example string.

Thanks for reaching out :+1:
