### ISSUE TITLE
How to run it in a windows environment 

### ISSUE THREAD

**Issue by akshay-s-madhwani** [leonwind/cli2cloud#27]
Tried running on Windows
installed perfectly, but after piping
says:

panic : send on closed channel

Please guide me on how to open this port/channel to stream it on the web

Any help would be much appreciated 
thanks

**Comment by leonwind** [comment]
Hey, thanks for reporting the bug!
Can you tell me which go version you are using? :)

**Comment by akshay-s-madhwani** [comment]
Hi, Im using go version 1.18.1 windows/amd64
